services:
  server:
    container_name: remote-docker-example-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=root/app
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/root/app


